# Generated by Django 5.0 on 2025-09-05 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='d',
            new_name='id',
        ),
    ]
